### ISSUE TITLE
model and weights

### ISSUE THREAD

**Issue by lygithub2017** [njvisionpower/Safety-Helmet-Wearing-Dataset#1]
can you provide your pre-trained model and weights?  because my computer have no gpu. So it may take a long long time to train. My teacher need me research object detection of helmet. in the school.  If you can, thanks a lot for you please...

**Comment by njvisionpower** [comment]
Hi, I will publish the pre-trained models and train/inference source code in thiss weel, thank you!

**Comment by njvisionpower** [comment]
@lygithub2017  I have uploaded the pre-trained models, you can try. Please help star this project if you feel well. Thanks.
