### ISSUE TITLE
请问windows下运行退出原因

### ISSUE THREAD

**Issue by yangbull** [njvisionpower/Safety-Helmet-Wearing-Dataset#10]
我在T430本子上的win10 x64跑这个程序，进入到train()函数后，没有任何提示就退出了。跟踪了一下，发现执行完这个语句后退出的：net.collect_params().reset_ctx(ctx) 。 可以讨教下原因吗？我检查了下我的cuda是8.0, python 3.6.6。是不是我下的mxnet-cu80/gluoncv/opencv/ 这3个包版本不对呢？

**Comment by yangbull** [comment]
我在train()的开头输出了参数信息： print("Enter train():", ctx, args)。以下是实际输出：
Enter train(): [gpu(0)] Namespace(batch_size=2, data_shape=416, dataset='voc', epochs=100, gpus='0', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='60, 80', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=6064, num_workers=1, resume='', save_interval=5, save_prefix='yolo3_darknet53_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, warmup_epochs=2, warmup_lr=0.0, wd=0.0005)

**Comment by njvisionpower** [comment]
印象中出过类似的问题，你能发一下你用的mxnet和gluoncv版本吗？

**Comment by yangbull** [comment]
谢谢回复！以下是 pip list 的输出：
Package                Version 
---------------------- --------
opencv-python          4.1.1.26
matplotlib             3.1.1   
mxnet-cu80             1.5.0   
gluoncv                0.5.0   
bleach                 1.5.0   
certifi                2019.9.1
chardet                3.0.4   
cycler                 0.10.0  
enum34                 1.1.6   
graphviz               0.8.4   
html5lib               0.999999
idna                   2.6     
kiwisolver             1.1.0   
lxml                   4.4.1   
Markdown               3.1.1   
numpy                  1.16.5  
Pillow                 6.2.0   
pip                    19.3    
protobuf               3.10.0  
pyparsing              2.4.2   
python-dateutil        2.8.0   
requests               2.18.4  
scipy                  1.3.1   
setuptools             39.0.1  
six                    1.12.0  
tensorflow-gpu         1.4.0   
tensorflow-tensorboard 0.4.0   
tqdm                   4.36.1  
urllib3                1.22    
Werkzeug               0.16.0  
wheel                  0.33.6

**Comment by njvisionpower** [comment]
印象中发现是第一个epoch训练后验证集测试的时候卡住了，不过后来更新版本之后这个问题没出现了。我当时在每个epoch训练打印loss后面：
https://github.com/njvisionpower/Safety-Helmet-Wearing-Dataset/blob/36d3a72f6d0fc25917a3fbb1e2176657bcdf3efe/train_yolo.py#L296
先保存模型，然后continue直接继续训练不去验证，比如：

        net.save_parameters(str(epoch) + '__.params') #每个epoch直接保存模型
        name1, loss1 = obj_metrics.get()
        name2, loss2 = center_metrics.get()
        name3, loss3 = scale_metrics.get()
        name4, loss4 = cls_metrics.get()
        logger.info('[Epoch {}] Training cost: {:.3f}, {}={:.3f}, {}={:.3f}, {}={:.3f}, {}={:.3f}'.format(
            epoch, (time.time()-tic), name1, loss1, name2, loss2, name3, loss3, name4, loss4))
        continue    #继续训练，而不验证

等epoch训练的比较多了以后手写脚本去验证。

**Comment by yangbull** [comment]
猜测是mxnet的版本问题，我换了mxnet-cu80==1.3.0 。单独测试了下：
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3), mx.gpu())

执行上面那个语句就退出来了。就是说 1.3.0 或者 1.5.0 都不行

**Comment by njvisionpower** [comment]
你试下能不能开始训练，gluoncv比较玄学，很多人都遇到过训练卡住的情况

**Comment by yangbull** [comment]
训练不了啊， 我执行到train()这就退出来了，而且没有任何提示。现在看应该是mxnet的问题，因为单独调试mxnet 也是没提示直接退出了

**Comment by njvisionpower** [comment]
我猜会不会和cuda版本有关，我用的是9.2，之前看到mxnet开发者在官方issue里提到cuda9以下都不推荐用了。

**Comment by yangbull** [comment]
我将train()函数出问题的语句先注释掉，然后按你的continue方式不验证，跳出来了。出现如下提示：
Traceback (most recent call last):                                                                                      
  File "e:\MyDoc\REPo\vDetect\train_yolo.py", line 364, in <module>                                                     
    train(net, train_data, val_data, eval_metric, ctx, args)                                                            
  File "e:\MyDoc\REPo\vDetect\train_yolo.py", line 272, in train                                                        
    for i, batch in enumerate(train_data):                                                                              
  File "E:\Programs\PyEnv\vdet\lib\site-packages\gluoncv\data\dataloader.py", line 283, in __iter__                     
    worker_fn=_worker_fn, prefetch=self._prefetch)                                                                      
  File "E:\Programs\PyEnv\vdet\lib\site-packages\gluoncv\data\dataloader.py", line 151, in __init__                     
    worker_fn=worker_fn, prefetch=0)                                                                                    
TypeError: __init__() got an unexpected keyword argument 'prefetch'                                                     
Exception ignored in: <bound method _MultiWorkerIter.__del__ of <gluoncv.data.dataloader._RandomTransformMultiWorkerIter
 object at 0x0000022ADE9046A0>>                                                                                         
Traceback (most recent call last):                                                                                      
  File "E:\Programs\PyEnv\vdet\lib\site-packages\mxnet\gluon\data\dataloader.py", line 224, in __del__                  
    self.shutdown()                                                                                                     
  File "E:\Programs\PyEnv\vdet\lib\site-packages\mxnet\gluon\data\dataloader.py", line 256, in shutdown                 
    if not self._shutdown:                                                                                              
AttributeError: '_RandomTransformMultiWorkerIter' object has no attribute '_shutdown'

**Comment by yangbull** [comment]
我的本子是ThinkPad T430。显卡是nvidia nvs 5400M ，应该装不上9.0吧，因为算力只有2.1。cuda 9.0的算力要求3.0以上

**Comment by yangbull** [comment]
不过这种猜测是有道理的，很可能和cuda版本有关

**Comment by njvisionpower** [comment]
这个issue建议去mxnet或者gluoncv官方提。
