### ISSUE TITLE
请教可以继续训练吗

### ISSUE THREAD

**Issue by yangbull** [njvisionpower/Safety-Helmet-Wearing-Dataset#11]
如果自己的数据已经标注完了，比如添加了若干类，能以您的权重文件继续训练吗？如果可以，应该采用哪种调用方式呢？我看参数中有个 --resume，这种方式报错，说参数不一致

**Comment by yangbull** [comment]
好的，谢谢。我仔细看下。我现在是把视频切成图片，然后用您的数据检测下，再还原成gif看下效果

**Comment by tsluqn** [comment]
> 好的，谢谢。我仔细看下。我现在是把视频切成图片，然后用您的数据检测下，再还原成gif看下效果

请问你是如何解决的呢
