### ISSUE TITLE
可以检测框控制颜色吗

### ISSUE THREAD

**Issue by yangbull** [njvisionpower/Safety-Helmet-Wearing-Dataset#13]
我拿您的权重文件检测图片，出来的检测框正向数据（带安全帽）是红色，不带是蓝色，如果我想让负向数据是红色，正向的不显示检测框（盒），要在入口函数传参吗？这个可以控制吗？我看入口函数有个colors参数，但不知道具体什么格式，能请教下调用方式吗？

**Comment by njvisionpower** [comment]
找到gluoncv封装的cv_plot_bbox函数，根据class_name改下面代码中的bcolor应该就可以了：
`cv2.rectangle(img, (xmin, ymin), (xmax, ymax), bcolor, 2)`

**Comment by yangbull** [comment]
您的意思是修改函数，不是传参？！汗！！

**Comment by njvisionpower** [comment]
gluoncv对于这些封装的小工具确实不怎么灵活，没有提供你说的这种改颜色的接口。还有个方法就是自己按照函数封装一个简单的

**Comment by yangbull** [comment]
谢谢指导。我原来以为调个接口就完事了呵呵，现在看不是那么回事。我仔细看了下原代码，要在cv2画框之前设定好bcolor，原代码没有判断根据不同类别画不同颜色。看来只能自己改造了，有点麻烦...
