### ISSUE TITLE
人头或者安全帽最小检测大小要求

### ISSUE THREAD

**Issue by yuqingbin** [njvisionpower/Safety-Helmet-Wearing-Dataset#14]
您好，想咨询下，与训练的模型，对于检测的人头或者安全帽所占的最小像素要求大约多少？

**Comment by njvisionpower** [comment]
Hi, 我训练用的标注数据，安全帽小像素的并不多(实际上安全帽和人头或者人脸还不太一样，一旦像素小很难判断出来是或不是，因为相对来说并没有那么明显的鉴别的特征，像鼻子眼睛嘴巴轮廓等等)，实际测试的时候如果要效果好的话最好大于40*40(我也没定性的测试过)。相对来说人头的话效果要好很多，你可以用一些小目标来试验下。
