### ISSUE TITLE
您好，可以检测视频吗

### ISSUE THREAD

**Issue by xiabandaka** [njvisionpower/Safety-Helmet-Wearing-Dataset#15]
前辈您好，请问这个源码可以改造成dlib调用摄像头的那种，实时分析监控图像吗，或者分析视频之类的。希望您有时间能够回复，麻烦您啦

**Comment by njvisionpower** [comment]
应该可以的，你就用opencv一帧一帧的取图像然后处理就可以了，不过Forward速度可能会比较慢，取决于模型的输入尺寸（不是视频图像的输入，是图像缩放后的尺寸大小）。

**Comment by xiabandaka** [comment]
好的谢谢您，我再研究研究，我觉得理论上可行，但是奈何水品有限，代码底子太薄，有不会的我再请教您

**Comment by xhaoshen** [comment]
你好，你的视频读取实现了嘛？

**Comment by tutu96177** [comment]
视频流读取可以阿，不过需要自己实现。
