### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by lqian** [njvisionpower/Safety-Helmet-Wearing-Dataset#18]
000377.xml has 4 dogs annotaions. but the 000377.jpg image does NOT have dog. The dataset download from baidu pan is correct?

<pre>
<object>
                <name>dog</name>
                <pose>Unspecified</pose>
                <truncated>0</truncated>
                <difficult>1</difficult>
                <bndbox>
                        <xmin>622</xmin>
                        <ymin>102</ymin>
                        <xmax>705</xmax>
                        <ymax>185</ymax>
                </bndbox>
        </object>
</pre>

**Comment by njvisionpower** [comment]
Thank you for your correction, I check the annotation for this image, it should be hat instead of dog. You can open issue if you found other annotation error for the data. I'll also modify the xml and update later.
