### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by DevinWang23** [njvisionpower/Safety-Helmet-Wearing-Dataset#19]
Hi,
When i tried to open the Annotations fold by labelImg, the folder cannot be opened and if i tried to directly open the iamge in folder, below error appears, I also googled it, but i have not found the solution yet, could you give me some tips? thanks in advance

`Traceback (most recent call last):
  File "labelImg.py", line 1278, in openFile
    self.loadFile(filename)
  File "labelImg.py", line 990, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
Aborted (core dumped)
`

Best Regards,
Devin

**Comment by njvisionpower** [comment]
Sorry I haven't met  this issue, may you can open PR in labelImg official repo.
