### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhaoguochuan** [njvisionpower/Safety-Helmet-Wearing-Dataset#2]
ax = utils.viz.cv_plot_bbox(orig_img, bboxes[0], scores[0], box_ids[0], class_names=net.classes,
                                thresh=args.threshold)  运行到这里报错了。
AttributeError: module 'gluoncv.utils.viz' has no attribute 'cv_plot_bbox' 请问这是为什么呢

**Comment by njvisionpower** [comment]
@zhaoguochuan 应该是gluoncv版本的原因，更新一下gluoncv版本：pip install gluoncv --upgrade --pre，然后应该就ok了
