### ISSUE TITLE
mxnet.base.MXNetError

### ISSUE THREAD

**Issue by By-he** [njvisionpower/Safety-Helmet-Wearing-Dataset#20]
Hello author, I would like to ask a question, when I was running test_yolo. Py, there was such a mistake: "mxnet.base.mxneterror: [19:26:26] C:\Jenkins\workspace\mxnet\mxnet\3rdparty\dmlc-core\ SRC \ IO \local_filesys. Cc :209: Check failed: allow_null:LocalFileSystem::Open "darknet.params": No such file or directory", how should I solve?Looking forward to your reply!

**Comment by njvisionpower** [comment]
Hi,
Obviously, you should download model from the driver link in readme.
