### ISSUE TITLE
Failed loading Parameter

### ISSUE THREAD

**Issue by By-he** [njvisionpower/Safety-Helmet-Wearing-Dataset#21]
Another problem is that after I modified the training path according to your instructions, there was such a problem as "AssertionError: Failed loading Parameter 'mobilenet0_dense0_bias' from saved params: shape incompatible expected (['hat', 'person'],) vs saved (1000,)", looking forward to your reply, thank you！

**Comment by njvisionpower** [comment]
Hi,
I wrote two way to forward, which way you used? I suspect you mixed up the model, for first way use the model in [Dynamic graph](https://pan.baidu.com/s/1dWNU_q59sw1a3TVtV7VXEg), for second way use model in [Symbol](https://pan.baidu.com/s/1EEdsjECJy_y00dekRre0eA).

**Comment by By-he** [comment]
Hello, thank you very much for your reply!On symbol. Py, I got good results.During your training steps, I downloaded the data set as required, and set the path and parameters, but there were still such problems as "AssertionError: Failed loading Parameter 'darknetv30_dense0_bias' from saved params:Shape incompatible expected (['hat', 'person'],) vs saved (1000,) ", which appears on line 325 of train_yolo. Py: "net = get_model(net_name, pretrained_base=True, classes=classes)"

**Comment by njvisionpower** [comment]
Hi,

You can change [this line](https://github.com/njvisionpower/Safety-Helmet-Wearing-Dataset/blob/f450a521649348a4786a5cebad6f93a4d1e937b4/train_yolo.py#L325)  as:
`net = get_model(net_name, pretrained_base=True)`

**Comment by By-he** [comment]
Thank you very much for your patience and the previous issues have been resolved. I downloaded the VOC2028 data set you gave, ran your "train_yolo.py" file, and used the "yolo3_darknet53_voc_best.params" file to execute "test_yolo.py". The parameters are your default parameters, but the accuracy is not very high . But using "test_symbol.py" and the model in the symbol to test, the accuracy is very good, what is the reason for this? Looking forward to your reply, thank you!

**Comment by njvisionpower** [comment]
I train the model with:
`python train_yolo.py --batch-size 4 -j 4 --warmup-epochs 2`
on  GTX1080Ti 32G PC with more than 100 epoches, the default command will use mixup to do data augmentation. Also I manually change smaller learning rate when observe the loss trend is not convergent. Just for reference.

**Comment by tenzinOvO** [comment]
您好，我用train_yolo.py训练了80个epoch，得到了一个params，然后再重新开始训练，在args.resume里把这个params加载进去，结果出现了下面这种问题，AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (75, 0, 1, 1) vs saved (21, 256, 1, 1)，是维度不匹配吗？请问是哪里出了问题呢，谢谢！

**Comment by Your-do** [comment]
> 您好，非常感谢您的回复！符号上。Py，我得到了很好的结果。在您的训练步骤中，我根据需要下载了数据集，并设置了路径和参数，但仍然存在诸如“断言错误：从保存的参数加载失败参数'darknetv30_dense0_bias'：形状不兼容的预期（['hat'，'person']，）与已保存的（1000，）”之类的问题，它出现在train_yolo的第325行。Py：“ net = get_model（net_name， pretrained_base=True， classes=classes）”



> 

hello, how did you implement the training on symbols？
