### ISSUE TITLE
upper case image extensions and noise label issue

### ISSUE THREAD

**Issue by loveunk** [njvisionpower/Safety-Helmet-Wearing-Dataset#22]
Following issues are found:
1. the upper case image extension 'JPG' causes errors.
2. the label 'dog' in image 000377.xml causes errors.

**Comment by njvisionpower** [comment]
Hi,
For first issue, I think different method take different rule to process upper or lower image extension format;
For second issue, there's already issue, see #18 , now I have modified the annotation xml and uploaded to Baidu drive in reandme link. Also I'll uploaded to Google drive soon. Thank you for your remind.

**Comment by loveunk** [comment]
@njvisionpower thanks for you reply. For me, the 1st issue happens when do training with MMDetection.
