### ISSUE TITLE
Model file Not Found on BaiduDrive Link - 404 Error

### ISSUE THREAD

**Issue by alishan2040** [njvisionpower/Safety-Helmet-Wearing-Dataset#24]
The link you provided to download Model file is giving 404 Error. Please provide any other link to download model file. 

Thanks

**Comment by njvisionpower** [comment]
Hi,

Now I also upload the model files to GoogleDrive, you can download pretrained models link in readme. Thanks.

**Comment by alishan2040** [comment]
link please?

**Comment by njvisionpower** [comment]
Try this [link](https://drive.google.com/open?id=1_0A-bQbsprzStefQOMiQpLn8JZBchqho)

**Comment by Monster-ux** [comment]
> 
> 
> Try this [link](https://drive.google.com/open?id=1_0A-bQbsprzStefQOMiQpLn8JZBchqho)

Hi
I have no permision to download from your GoogleDrive link, can you share  a new BaiduDrive link?
Thanks

**Comment by njvisionpower** [comment]
> > Try this [link](https://drive.google.com/open?id=1_0A-bQbsprzStefQOMiQpLn8JZBchqho)
> 
> Hi
> I have no permision to download from your GoogleDrive link, can you share a new BaiduDrive link?
> Thanks

Hi 
You can try [this model](https://pan.baidu.com/s/1dWNU_q59sw1a3TVtV7VXEg), or if you want inference with symbol, you can try [this model](https://pan.baidu.com/s/1EEdsjECJy_y00dekRre0eA)

**Comment by AatishLanghee** [comment]
@njvisionpower  Can you share the models on aatishlanghee40@gmail.com
