### ISSUE TITLE
运行结果似乎没有做NMS，可是您在readme里面是有nms的效果的，不知道我什么地方做的不对，谢谢

### ISSUE THREAD

**Issue by northeastsquare** [njvisionpower/Safety-Helmet-Wearing-Dataset#25]
python test_yolo.py执行结果如下，感觉没有nms, 什么地方需要设置吗？谢谢
![image](https://user-images.githubusercontent.com/3086078/70495023-52dc8380-1b48-11ea-9d57-98a4087b9100.png)

**Comment by njvisionpower** [comment]
我怀疑是因为你读的图像和保存的图像用的同一个名字。。。然后每次预测是在画完框的结果图像上继续预测的。。。。
