### ISSUE TITLE
map是86%，为啥推理效果展示的那么好呀？推理有啥参数技巧吗

### ISSUE THREAD

**Issue by xautzxc** [njvisionpower/Safety-Helmet-Wearing-Dataset#26]
你好，看了一下map是86%，为啥推理效果展示的那么好呀？推理有啥参数技巧吗？
我用keras-yolo-mobilenetv1训练了你提供的数据集，没有这么好的效果。虽然我的map也有80+。

**Comment by njvisionpower** [comment]
1.mobilenet这种backbone肯定不如更深的网络，像darknet53，resnet50这种；
2.gluoncv训练的一些技巧，可以参考[链接](https://arxiv.org/abs/1902.04103)，结合源码看，有很多trick。

**Comment by xautzxc** [comment]
因为是要在端设备实现的，资源有限，用不了那么深的网络，而且有一些算子不支持。就是感觉你的infer挺好的，但map也就还好。

**Comment by Single430** [comment]
mark
