### ISSUE TITLE
About “json” file

### ISSUE THREAD

**Issue by By-he** [njvisionpower/Safety-Helmet-Wearing-Dataset#27]
Hello, thank you very much for your previous answer. I want to ask you how to generate the json file in the symbol file. After training, only the following: "yolo3_darknet53_voc_best.params", "yolo3_darknet53_voc_best_map" and "yolo3_darknet53_voc_train", Looking forward to your reply, thank you!

**Comment by njvisionpower** [comment]
You can export json file like this demo:

from gluoncv import model_zoo, data, utils
import mxnet as mx

im_fname = utils.download('https://github.com/dmlc/web-data/blob/master/' +
                           'gluoncv/detection/street_small.jpg?raw=true',
                           path='street_small.jpg')
ctx = mx.gpu()
x, img = data.transforms.presets.yolo.load_test(im_fname, short=512)
x = x.as_in_context(ctx)
net = model_zoo.get_model('yolo3_darknet53_voc', pretrained=True)
net.hybridize()
class_IDs, scores, bounding_boxs = net(x)
net.export('./yolov3', epoch=0)
