### ISSUE TITLE
训练所需配置

### ISSUE THREAD

**Issue by Zpadger** [njvisionpower/Safety-Helmet-Wearing-Dataset#28]
作者您好，非常感谢开源这么棒的模型和训练方法。如果我要训练自己的数据集，请问对于电脑配置的要求是怎么样的？一般要训练多长时间呢？我的电脑配置是：

> 内存：16G

> 处理器：Intel® Core™ i5-9400F CPU @ 2.90GHz × 6 

> 显卡：GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by njvisionpower** [comment]
我用的1080ti +32G内存，差不多训练了七八个小时吧（开多线程持续训练没卡住的情况），这个要看具体的机器，你的配置我看至少也要半天时间，实际训练的时候发现CPU load数据反而成了瓶颈，把线程数开大点（视CPU核心数而定）会很大程度加快的，仅供参考。

**Comment by Zpadger** [comment]
好的非常感谢您的建议
