### ISSUE TITLE
数据集开源协议

### ISSUE THREAD

**Issue by largeword** [njvisionpower/Safety-Helmet-Wearing-Dataset#29]
作者你好，请问一下您制作的安全帽训练数据集采用何种开源协议？我们学校的比赛正好需要用到

**Comment by njvisionpower** [comment]
你可以使用MIT license，谢谢！

**Comment by dragonbra** [comment]
> 你可以使用MIT license，谢谢！

您好，请问您知道您的数据集被用于[中国大学生服务外包大赛](http://www.fwwb.org.cn)赛题“【A05】基于人工智能的视觉识别技术【文思海辉】”官方发布的训练数据集吗？
请问这套数据的标注和图片是您自己处理的，还是别处已有的呢？
