### ISSUE TITLE
训练参数

### ISSUE THREAD

**Issue by wang-xinyu** [njvisionpower/Safety-Helmet-Wearing-Dataset#30]
您好，感谢分享！请问能否再分享一下训练时的超参数配置？包括batch size，epoch，learning rate等。

**Comment by njvisionpower** [comment]
python train_yolo.py --batch-size 4 -j 4 --warmup-epochs 2。  learning rate做2个epoch的warm up过度到0.001，默认配置会开启mixup做数据增强，你可以视你的显存增加或者减小batch size。

**Comment by wang-xinyu** [comment]
thanks bro
