### ISSUE TITLE
请教下在训练中出现的问题

### ISSUE THREAD

**Issue by butterniu** [njvisionpower/Safety-Helmet-Wearing-Dataset#34]
我在加载网络：net = get_model(net_name, pretrained_base=True, classes=classes)
出现了AssertionError: Failed loading Parameter 'darknetv30_dense0_bias' from saved params: shape incompatible expected (['hat', 'person'],) vs saved (1000,)的问题，暂时没有别的解决方法，net_name为yolo3_darknet53_voc，和您加载的同一个，但出现了这个问题，让我有些难过

**Comment by njvisionpower** [comment]
你可以参考下这个issue: #21 ，和你出现的问题类似。

**Comment by butterniu** [comment]
非常感谢您的回复，按照您的方法已经成功解决了

**Comment by butterniu** [comment]
我想再请教您两个问题
1.我根据您的代码进行了训练，但发现训练的结果并不是很好，我也修改了参数，想请问您是不是对文件中途有修改
2.然后，我想在您的训练基础上继续进行训练，但发现训练时追加 --resume darknet.params，
但会有错误发生
AssertionError: Failed loading Parameter 'yolov30_yolooutputv30_conv0_weight' from saved params: shape incompatible expected (75, 0, 1, 1) vs saved (21, 1024, 1, 1)
，请问如何在您的模型上进行加强训练呢

**Comment by njvisionpower** [comment]
1.不知道你训练了多少epoch，我用单1080ti前后陆续训练了差不多100个epoch，训练过程中手动调小了学习率；
2.可以参考下这个issue: #12

**Comment by butterniu** [comment]
非常感谢您对我的解答，现在运行成功，正在进行训练，由于设备不太好，需要训练时间就比较长，哈哈哈
