### ISSUE TITLE
about scut-head

### ISSUE THREAD

**Issue by wang-xinyu** [njvisionpower/Safety-Helmet-Wearing-Dataset#35]
您这里用了scut-head，但是我发现图片数量对不上，scut-head原有PartA 2000张，PartB 2405张，但是您这里PartA 1999张，PartB 2341张。
请问是删掉了一些质量不好的图片吗？

**Comment by njvisionpower** [comment]
是的，记得我最开始做的时候手动写了脚本，判断图像和标签的格式是否正确，比如判断明显的标注错误、是否存在没有object的xml情况、图像类型等等。

**Comment by wang-xinyu** [comment]
哦哦 好的
