### ISSUE TITLE
检测输出结果咨询

### ISSUE THREAD

**Issue by yuqingbin** [njvisionpower/Safety-Helmet-Wearing-Dataset#4]
你好，我是目标检测新手，您那个test_yolo.py 输出是检测框好的图片，我怎么获取一张图片检测输出的结果，就是python 代码中取到识别的标签和位置

**Comment by njvisionpower** [comment]
请参考mxnet自己封装的画图函数utils.viz.cv_plot_bbox，见这一行[代码](https://github.com/dmlc/gluon-cv/blob/ee602b6f68f0bdd19f449a86955697f8f0a2d54c/gluoncv/utils/viz/bbox.py#L188)，这个就是根据阈值筛选出来的bounding box左上和右下坐标。

**Comment by yuqingbin** [comment]
> 请参考mxnet自己封装的画图函数utils.viz.cv_plot_bbox，见这一行[代码](https://github.com/dmlc/gluon-cv/blob/ee602b6f68f0bdd19f449a86955697f8f0a2d54c/gluoncv/utils/viz/bbox.py#L188)，这个就是根据阈值筛选出来的bounding box左上和右下坐标。

感谢，已解决！
