### ISSUE TITLE
从预训练权重开始训练的问题

### ISSUE THREAD

**Issue by tenzinOvO** [njvisionpower/Safety-Helmet-Wearing-Dataset#48]
您好，我用train_yolo.py训练了80个epoch，得到了一个params，然后再重新开始训练，在args.resume里把这个params加载进去，结果出现了下面这种问题，AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (75, 0, 1, 1) vs saved (21, 256, 1, 1)，是维度不匹配吗？请问是哪里出了问题呢，谢谢！

**Comment by yunchangxiaoguan** [comment]
> 您好，我用train_yolo.py训练了80个epoch，得到了一个params，然后再重新开始训练，在args.resume里把这个params加载进去，结果出现了下面这种问题，AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (75, 0, 1, 1) vs saved (21, 256, 1, 1)，是维度不匹配吗？请问是哪里出了问题呢，谢谢！

大佬，请问你的问题解决了嘛，我也在想重新训练呢
