### ISSUE TITLE
about train? 

### ISSUE THREAD

**Issue by weixing1994** [njvisionpower/Safety-Helmet-Wearing-Dataset#5]
Can you provide a training program?

**Comment by njvisionpower** [comment]
Hi, I‘ll upload the train file soon, as some code should be little modified.

**Comment by HirataYurina** [comment]
if you can upload the train file, i can learn more about yolo3. But i always appreciate you.

**Comment by njvisionpower** [comment]
@weixing1994 @HirataYurina  I have upload train file, please see "How to train".
