### ISSUE TITLE
Output of train_yolo.py just contains .params, how to get .json file

### ISSUE THREAD

**Issue by LoryMANG** [njvisionpower/Safety-Helmet-Wearing-Dataset#51]
Dear author:
When i run the train_yolo.py, it just create the .params files and some log files.How can i get the json file?

**Comment by Andrawzyf** [comment]
> Dear author:
> When i run the train_yolo.py, it just create the .params files and some log files.How can i get the json file?

@LoryMANG hello，have you saved the issue？
