### ISSUE TITLE
加载预训练模型或继续训练报错

### ISSUE THREAD

**Issue by yunchangxiaoguan** [njvisionpower/Safety-Helmet-Wearing-Dataset#56]
用--resume加载模型
加载darknetparams会报错：
AssertionError: restore_prefix is 'yolov30_' but Parameters name 'darknetv30_conv0_weight' does not start with 'yolov30_'
加载自己训练的模型会报错：
AssertionError: Failed loading Parameter 'yolov30_yolooutputv30_conv0_weight' from saved params: shape incompatible expected (75, 0, 1, 1) vs saved (21, 1024, 1, 1)

已经把class=class这个参数删掉了
这到底要怎么解决呢

**Comment by zongoalbert** [comment]
could you please send me the model : zakariaharakat@gmail.com

**Comment by wdh234** [comment]
参考test_yolo.py加载模型加载模型再训练.

**Comment by yunchangxiaoguan** [comment]
> 参考test_yolo.py加载模型加载模型再训练.

嗯呢，谢谢，已经解决了
