### ISSUE TITLE
YOLO3 异常退出

### ISSUE THREAD

**Issue by yuanbing** [njvisionpower/Safety-Helmet-Wearing-Dataset#8]
我试图运行test_yolo.py. 但是我得到如下的错误：

python test-yolo.py 
use darknet to extract feature
Illegal instruction (core dumped)

这是我的conda环境：

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_mutex_mxnet              0.0.40                      mkl  
asn1crypto                1.0.1                    py37_0  
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.8.28                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2019.9.11                py37_0  
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
cryptography              2.7              py37h1ba5d50_0  
cycler                    0.10.0                   pypi_0    pypi
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.9.1                h8a8886c_1  
glib                      2.56.2               hd408876_0  
gluoncv                   0.5.0                    pypi_0    pypi
graphite2                 1.3.13               h23475e2_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.4                      243  
jasper                    2.0.14               h07fcdf6_1  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libmklml                  2019.0.5                      0  
libmxnet                  1.5.0            mkl_hfe83b78_0  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
matplotlib                3.1.1                    pypi_0    pypi
mkl                       2019.4                      243  
mkl-dnn                   0.19                 hfd86e86_1  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.14           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
mxnet                     1.5.0                hea8a0af_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.2                   pypi_0    pypi
numpy-base                1.17.2           py37hde5b4d6_0  
opencv-contrib-python     4.1.1.26                 pypi_0    pypi
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               h7b6447c_2  
pcre                      8.43                 he6710b0_0  
pillow                    6.2.0                    pypi_0    pypi
pip                       19.2.3                   py37_0  
pixman                    0.38.0               h7b6447c_0  
py-mxnet                  1.5.0            py37hc738527_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.2                    pypi_0    pypi
pysocks                   1.7.1                    py37_0  
python                    3.7.4                h265db76_1  
python-dateutil           2.8.0                    pypi_0    pypi
python-graphviz           0.8.4                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_0  
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.4.0                   py37_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.30.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.36.1                   pypi_0    pypi
urllib3                   1.25.6                   pypi_0    pypi
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

我的ＣＰＵ是intel xeon E5-2680

**Comment by njvisionpower** [comment]
你安装mxnet，gluoncv的命令，以及版本是多少？这种情况应该和mxnet安装的版本有关

**Comment by yuanbing** [comment]
for mxnet, I use "conda install mxnet", the version is 1.5.0
for gluoncv, I use "pip install gluoncv", the version is 0.5.0

**Comment by njvisionpower** [comment]
不知道你现在运行成功了没？出现这种问题可能是MXNet某个版本和CPU指令集不兼容。可以试一下[这个链接](https://gluon-cv.mxnet.io/install.html)尝试换个版本试试，我之前用mxnet 的MKL-DNN貌似也出现过这种情况的。
