### ISSUE TITLE
请问下载的models应该放在什么路径下？

### ISSUE THREAD

**Issue by thinkinds** [njvisionpower/Safety-Helmet-Wearing-Dataset#9]
我想使用预训练模型进行inference，下载了models，但是运行python test_yolo.py就提示模型找不到，开始从网上下载

**Comment by thinkinds** [comment]
也许我应该下symbols，运行test_symbol.py，这就正常了

**Comment by njvisionpower** [comment]
可以直接用symbol，相当于直接从本地模型里解析加载，这样简单点。顺便说下，用model_zoo正常情况指定pretrained=False不需要下载预训练模型的，可能是mxnet自己的机制问题，这里还是要去下载，暂时不用管了。

**Comment by thinkinds** [comment]
再请教一个问题，如果用mxnet model server部署你的模型，signature.json模型的签名该怎么写？

**Comment by njvisionpower** [comment]
抱歉，MMS我也不熟悉。。
